services:
  productpage:
    build: .
    image: ghcr.io/thanuchcha1603/bookinfo-details:dev
    ports:
      - "8083:8083"
    environment:
      DETAILS_HOSTNAME: http://details:8081/ 
      RATINGS_HOSTNAME: http://ratings:8080/
      REVIEWS_HOSTNAME: http://reviews:9080/
      FLOOD_FACTOR: 0